name = "gdrive-acc"
main = "./worker.js"
compatibility_date = "2024-03-20"

# 环境变量配置
[vars]
# 可以在这里添加环境变量

# 构建配置
[build]
command = ""  # 如果有构建步骤，可以在这里指定命令

# 触发器配置
[triggers]
crons = []  # 可以在这里添加定时任务

# 路由配置
routes = ["*/*"]